routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/medlife-dashboard', 'HomeController@index');


Route::resource('card', 'AdminCardController');
Route::resource('subpage', 'AdminSubpageController');
Route::resource('lang', 'LanguagesController');
Route::resource('page', 'AdminPagesController');
Route::resource('text', 'AdminTextController');
Route::get('/pg/{pageId}/{langID}', 'PagesController@getPage')->name('getPage');
Route::put('page-update/{pageID}', 'AdminPagesController@switchNavActive')->name('page.update.nav');
Route::put('page-update-welcome/{pageID}', 'AdminPagesController@switchWelcome')->name('page.update.welcome');
Route::put('subpage-update/{subpageID}', 'AdminSubpageController@switchDropActive')->name('subpage.update.drop');
Route::post('mail', 'MessagesController@store')->name('mail');
Route::get('/{langID?}', "PagesController@WelcomePage")->name('wellcome');

resources/views/admin_views/dashboard.blade.php
@extends('layouts.admin.dashboard')

@section('content')
<div class="row">
        <div class="col-md-1 ml-auto">
            <button class="btn btn-primary btn-rounded" data-target="#pageCreateModal" data-toggle="modal"><i
                    class="fas fa-plus fs"></i></button>
        </div>
</div>

<div class="row">
    @foreach ($pages as $page)
        <div class="col-md-4">
            <div class="card-deck">
                <div class="card mt-4 h-card-dashboard">
                    <img class="card-img-top img-size" src="/pages/images/{{$page->img}}"  alt="Card image cap">
                    <div class="card-body">
                             <h3 class="card-title text-center">{{$page->route_name}}</h3>
                      <a href="{{route('card.show', $page->id)}}" class="btn btn-outline-primary my-1 btn-block font-btn">Carduri</a>
                      <a href="{{route('subpage.show', $page->id)}}" class="btn btn-outline-info my-1 btn-block font-btn">Subpagini</a>
                      <a href="{{route('page.edit', $page->id)}}" class="btn btn-outline-success my-1 btn-block font-btn">Editarea Contentului</a>
                    <div class="row">
                            <button class="btn btn-success col ml-3 edit-page-btn mr-1"  data-target="#page-edit-modal-{{$page->id}}" data-toggle="modal" data-url='{{route("page.update",$page->id)}}'  data-route = "{{$page->route_name}}">
                                <i class="fas fa-edit"></i>
                            </button>
                            <button class="btn btn-danger col mr-3 delete-page-btn ml-1" 
                                data-url="{{route('page.destroy', $page->id)}}">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                    </div>
                     <div class="row mt-2 nav-active-div">
                         <div class="col-12 text-center">
                            <h2>Ordinea {{$page->index}}</h2>
                         </div>
                             <div class="custom-control custom-switch text-right ml-auto">
                                    <input type="checkbox" class="custom-control-input nav-show-page-checkbox " {{$page->nav_active == 1 ? 'checked' : ''}} id="switch-{{$page->id}}"  data-id="{{$page->id}}" data-url="{{route('page.update.nav', $page->id)}}">
                                    <label class="custom-control-label" for="switch-{{$page->id}}" >Afisare pe bara de meniu</label>
                             </div>
                             <div class="custom-control custom-switch text-right ml-auto">
                                <input type="checkbox" class="custom-control-input welcome-show-page-checkbox " {{$page->welcome_active == 1 ? 'checked' : ''}} id="switch-welcome-{{$page->id}}"  data-id="{{$page->id}}" data-url="{{route('page.update.welcome', $page->id)}}">
                                <label class="custom-control-label" for="switch-welcome-{{$page->id}}" >Afisare pe pagina principala</label>
                            </div>
                     </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="page-edit-modal-{{$page->id}}" tabindex="-1" role="dialog">
            
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle" style="color:black;">Modificarea paginii</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
        
                    <form data-url="{{route('page.update', $page->id)}}" enctype="multipart/form-data" data-id = "{{$page->id}}" method="POST" class='edit-page-form'>
                        @csrf
                        @method("PATCH")
                        <div class="modal-body">
                            <label for=".add-page-index routeEdit" class="mt-2 page-ord-label mt-4">Denumirea rutei</label>
                            <input type="text" class="form-control " id="route-edit-{{$page->id}}" value="{{$page->route_name}}">
                            <input type="file" class="mt-4" name='image'>
                            <br>
                            <label for=".add-page-index" class="mt-2 page-ord-label mt-4">Ordinea paginii</label>
                            <select class="custom-select" id="add-page-index-{{$page->id}}">
                                    @for ($i = 1; $i <= 7; $i++)
                                        @if($i == $page->index)
                                         <option value="{{$page->index}}" selected>{{$page->index}}</option>
                                         @else 
                                         <option value="{{$i}}">{{$i}}</option>
                                        @endif
                                    @endfor
                            </select>
                            <br>
                        </div>
                        <div class="modal-footer container">
                                
                            <button class="btn btn-outline-primary add-page-btn" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach
    
</div>
<div class="modal fade" id="pageCreateModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle" style="color:black;">Crearea paginii</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form data-url="{{route("page.store")}}" enctype="multipart/form-data" id='add-page-form'>
                @csrf
                <div class="modal-body">
                    <input type="text" class="form-control mt-4" placeholder="Denumirea rutei" id="route">
                    <input type="text" class="form-control mt-4" placeholder="Denumirea paginii" id="title">
                    <textarea class="form-control mt-4" placeholder="Descriptia" rows="3" id="description"></textarea>
                    <input type="file" class="mt-4" name='image'>
                    <br>

                    <div class="custom-control custom-switch mt-4 ml-2">
                            <input type="checkbox" class="custom-control-input main-page-checkbox" id="customSwitch1">
                            <label class="custom-control-label" for="customSwitch1">Pagina Secundara</label>
                    </div>
                    <select class="custom-select mt-4 d-none add-main-page">
                            @foreach ($pages as $page)
                            <option value="{{$page->id}}" id="page-option">{{$page->route_name}}</option>
                            @endforeach
                    </select>
                    <select class="custom-select mt-4 add-page-lang">
                        @foreach ($langs as $lang)
                        <option value="{{$lang->id}}">{{$lang->language}}</option>
                        @endforeach
                    </select>
                    <br>
                    <label for=".add-page-index" class="mt-2 page-ord-label">Ordinea paginii</label>
                    <select class="custom-select add-page-index">
                        @for ($i = 1; $i <= 7; $i++)
                            <option value="{{$i}}">{{$i}}</option>
                        @endfor
                    </select>
                </div>
                <div class="modal-footer container">
                    <button class="btn btn-outline-primary add-page-btn" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


@endsection

resources/views/admin_views/showCards.blade.php
@extends('layouts.admin.dashboard')

@section('content')
<div class="row">
    <div class="col-md-1 ml-auto">
        <button class="btn btn-primary btn-rounded" data-target="#card-create-modal" data-toggle="modal"><i
                class="fas fa-plus fs"></i></button>
    </div>
</div>
<div class="row">
    @foreach ($cards as $card)
    <div class="col-md-4 ">
        <div class="card-deck">
            <div class="card mt-4">
                <img class="card-img-top img-size" src="/pages/images/{{$page->img}}"  alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title text-center">{{$card->title}}</h3>
                    <p class="card-text mt-2 card-text-font text-center">{{$card->description}}</p>
                    <hr>
                    <div class="row mt-3">
                        <div class="col h3">
                            {{$card->language->language}}
                        </div>
                        <button class="btn btn-success ml-auto mr-1 edit-card-btn" data-target="#card-edit-modal-{{$card->id}}" data-toggle="modal">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button class="btn btn-danger mr-1 delete-card-btn" data-url="{{route('card.destroy', $card->id)}}">
                            <i class="fas fa-trash-alt"></i>
                        </button>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <form data-url="{{route("card.update", $card->id)}}" enctype="multipart/form-data" method="POST" class='edit-card-form' data-id="{{$card->id}}">
        @csrf
        @method('PATCH')
        <div class="modal fade" id="card-edit-modal-{{$card->id}}" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle" style="color:black;">Crearea paginii pentru</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <input type="text" class="form-control mt-4" value={{$card->title}} id="title-{{$card->id}}">
                            <textarea class="form-control mt-4" rows="3" id="description-{{$card->id}}">{{$card->description}}</textarea>
                            <select class="custom-select mt-4 edit-card-lang-{{$card->id}}">
                                @foreach ($langs as $lang)
                                <option value="{{$lang->id}}">{{$lang->language}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="modal-footer container">
                            <button  class="btn btn-outline-primary edit-card-btn"  type="submit">Save</button>
                        </div>
                    </div>
                </div>
            </div>
    </form>

    @endforeach
</div>



<div class="modal fade" id="card-create-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle" style="color:black;">Crearea paginii pentru</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="text" class="form-control mt-4" placeholder="Titlul" id="title">
                <textarea class="form-control mt-4" placeholder="Descriptia" rows="3" id="description"></textarea>
                <select class="custom-select mt-4 add-card-lang">
                    @foreach ($langs as $lang)
                    <option value="{{$lang->id}}">{{$lang->language}}</option>
                    @endforeach
                </select>
            </div>
            <div class="modal-footer container">
                <button data-id="{{$page->id}}" class="btn btn-outline-primary add-card-btn" data-url="{{route("card.store")}}" type="submit">Save</button>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin_views/showEditor.blade.php
@extends('layouts.admin.dashboard')


@section('content')
<div class="row">
        <div class="col-md-1 ml-auto">
            <button class="btn btn-primary btn-rounded" data-target="#add-text" data-toggle="modal"><i
                    class="fas fa-plus fs"></i></button>
        </div>
</div>

<div class="row">
    @foreach ($texts as $text)
<div class="card col m-5" style="width: 30rem;">
        <div class="card-body">
          <h5 class="card-title">{{$text->page->route_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">Limba: {{$text->language->language}}</h6>
          <a href="#" class="card-link" data-target="#edit-text-{{$text->id}}" data-toggle="modal">Editare</a>
        </div>
      </div>
      <div class="container-fluid">
            <div class="modal fade modal-center" id="edit-text-{{$text->id}}" tabindex="-1" role="dialog" aria-labelledby="add-text-label"
                aria-hidden="true" style="position:absolute; left:10%;">
                <div class="modal-dialog modal-dialog-custom modal-dialog-centered modal-lg " role="document">
                    <div class="modal-content md-lg">
                        <div class="modal-header">
                            <h5 class="modal-title" id="add-text-label">Editarea textului</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form action="{{ route('text.update', $text->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="modal-body">
                                <h3 class='route mb-3'>{{$page->route_name}}( Limba: {{$text->language->language}} )</h3>
                                <button type="submit" class="btn btn-outline-primary mb-3 ">Save</button>
                                <input type="hidden" name="page_id" value="{{$page->id}}">
                                <textarea class="editor" data-id = "{{$text->id}}" class="editor-textarea" name="description" required>{!!$text->description!!}</textarea>
                                <script>
                                            $(".editor").summernote({
                                                tabsize: 2,
                                                height: 500,
                                                width: 1200
                                            });
                                </script>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
@endforeach
</div>


<div class="container-fluid">
    <div class="modal fade modal-center" id="add-text" tabindex="-1" role="dialog" aria-labelledby="add-text-label"
        aria-hidden="true" style="position:absolute; left:10%;">
        <div class="modal-dialog modal-dialog-custom modal-dialog-centered modal-lg " role="document">
            <div class="modal-content md-lg">
                <div class="modal-header">
                    <h5 class="modal-title" id="add-text-label">Crearea textului</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('text.store')}}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <h3 class='route'>{{$page->route_name}}</h3>
                        <input type="hidden" name="page_id" value="{{$page->id}}">
                        <div class="row mx-3">
                            <button type="submit" class="btn btn-outline-primary my-4 ml-3">Save</button>
                            <div class="col-12">
                                <select class="custom-select add-page-lang mb-5" name="lang_id">
                                    @foreach ($langs as $lang)
                                    <option value="{{$lang->id}}">{{$lang->language}}</option>
                                    @endforeach
                            </div>
                            </select>
                        </div>
                        <textarea id="editor2" name="description" required></textarea>
                        <script>
                            $('#editor2').summernote({
                                tabsize: 2,
                                height: 500,
                                width: 1200
                            });
                            
                        </script>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin_views/showSubpages.blade.php
@extends('layouts.admin.dashboard')

@section('content')
<div class="row">
    @foreach ($subpages as $subpage)
        <div class="col-md-4">
            <div class="card-deck">
                <div class="card mt-4 h-card-dashboard">
                    <img class="card-img-top img-size" src="/pages/images/{{$subpage->img}}"  alt="Card image cap">
                    <div class="card-body">
                             <h3 class="card-title text-center mt-2">{{$subpage->route_name}}</h3>
                      <a href="{{route('card.show', $subpage->id)}}" class="btn btn-outline-primary my-1 btn-block font-btn mt-5">Carduri</a>
                      <a href="{{route('page.edit', $subpage->id)}}" class="btn btn-outline-success my-1 btn-block font-btn">Editarea Contentului</a>
                    <div class="row ">
                            <button class="btn btn-success col ml-3 edit-subpage-btn mr-1"  data-target="#subpage-edit-modal-{{$subpage->id}}" data-toggle="modal" data-url='{{route("subpage.update",$subpage->id)}}'  data-route = "{{$subpage->route_name}}">
                                <i class="fas fa-edit"></i>
                            </button>
                            <button class="btn btn-danger col mr-3 delete-subpage-btn ml-1" 
                                data-url="{{route('subpage.destroy', $subpage->id)}}">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                    </div>
                    <div class="row">
                        <div class="custom-control custom-switch ml-auto mt-3">
                            <input type="checkbox" class="custom-control-input drop-show-page-checkbox "
                                {{$subpage->drop_active == 1 ? 'checked' : ''}} id="switch-{{$subpage->id}}"
                                data-id="{{$subpage->id}}" data-url="{{route('subpage.update.drop', $subpage->id)}}">
                            <label class="custom-control-label" for="switch-{{$subpage->id}}">Afisare ca subpagina</label>
                        </div>
                        <div class="custom-control custom-switch text-right ml-auto mt-3">
                            <input type="checkbox" class="custom-control-input welcome-show-page-checkbox " {{$subpage->welcome_active == 1 ? 'checked' : ''}} id="switch-welcome-{{$subpage->id}}"  data-id="{{$subpage->id}}" data-url="{{route('page.update.welcome', $subpage->id)}}">
                            <label class="custom-control-label" for="switch-welcome-{{$subpage->id}}" >Afisare pe pagina principala</label>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
             <div class="modal fade" id="subpage-edit-modal-{{$subpage->id}}" tabindex="-1" role="dialog">
            
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle" style="color:black;">Modificarea paginii</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form data-url="{{route('subpage.update', $subpage->id)}}" enctype="multipart/form-data" data-id = "{{$subpage->id}}" method="POST" class='edit-page-form'>
                        @csrf
                        @method("PATCH")
                        <div class="modal-body">
                            <label for=".add-page-index routeEdit" class="mt-2 page-ord-label mt-4">Denumirea rutei</label>
                            <input type="text" class="form-control " id="route-edit-{{$subpage->id}}" value="{{$subpage->route_name}}">
                            <input type="file" class="mt-4" name='image'>
                            <br>
                        </div>
                     
                        <div class="modal-footer container">
                                
                            <button class="btn btn-outline-primary add-page-btn" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach
</div>
@endsection